export const data = [
  {
    logo: "../../assets/starter.png",
    type: "Starter",
    cost: "Free",
    period: "per month",
    featured: false,
    benefits: [
      { text: "Full courses library", activated: true },
      { text: "A new daily meditation", activated: true },
      { text: "Access to the meditation guru", activated: true },
      { text: "Sleep podcasts and exercises", activated: false },
      { text: "Mindfulness exercises", activated: false },
      { text: "Guided meditations", activated: false },
      { text: "Cooking recipes", activated: false },
    ],
    buttonText: "Get Started",
  },
  {
    logo: "../../assets/pro.png",
    type: "Pro",
    cost: "$49",
    period: "per month",
    featured: true,
    benefits: [
      { text: "Full courses library", activated: true },
      { text: "A new daily meditation", activated: true },
      { text: "Access to the meditation guru", activated: true },
      { text: "Sleep podcasts and exercises", activated: true },
      { text: "Mindfulness exercises", activated: true },
      { text: "Guided meditations", activated: false },
      { text: "Cooking recipes", activated: false },
    ],
    buttonText: "Become a Pro",
  },
  {
    logo: "../../assets/team.png",
    type: "Teams",
    cost: "$99",
    period: "per month",
    featured: false,
    benefits: [
      { text: "Full courses library", activated: true },
      { text: "A new daily meditation", activated: true },
      { text: "Access to the meditation guru", activated: true },
      { text: "Sleep podcasts and exercises", activated: true },
      { text: "Mindfulness exercises", activated: true },
      { text: "Guided meditations", activated: true },
      { text: "Cooking recipes", activated: true },
    ],
    buttonText: "Get Teams",
  },
];
